# -*- coding: utf-8 -*-
"""BERTofic_(맥락반영) (메타정보포함) (토픽별 댓글 원문 수집) 0617.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I85DKhimwx9TgMdgVPB_GCUA7EuRpe7x

# 유튜브 데이터 기반 BERTopic 혼합 연구(Mixed Methods) 파이프라인

본 노트북은 YouTube Data API를 활용한 소셜 미디어 데이터 수집부터, BERTopic 모델 학습 및 질적/양적 통합 산출물(Joint Display) 도출까지의 전 과정을 자동화합니다. 런타임 초기화 시 데이터 유실을 방지하기 위해 단계별 체크포인트(Checkpoint)가 적용되어 있습니다.

## 📌 주요 설정 및 주의사항
1. **API 키 보안 설정**: 좌측 메뉴의 열쇠 모양 아이콘(Secrets)을 클릭하고, 이름에 `YOUTUBE_API_KEY`, 값에 발급받은 API 키를 입력한 후 '노트북 액세스'를 활성화하십시오.
2. **작업 경로**: 모든 산출물은 `구글 드라이브/MyDrive/AI통합교육` 폴더에 자동으로 저장됩니다.

## 🔄 런타임 재시작(에러 또는 세션 만료) 시 복구 가이드
구글 코랩 환경의 한계로 인해 런타임이 끊겼을 경우, 진행되었던 단계에 따라 아래의 순서로 셀을 실행하여 작업을 안전하게 재개(Resume)할 수 있습니다.

* **상황 A. 데이터 수집(Cell 2) 도중 끊긴 경우**
  * `[Cell 1] 환경 설정` 실행 ➔ `[Cell 2] 데이터 수집` 실행
  * *(설명: 수집 로직이 드라이브의 CSV 파일을 확인하여, 이미 수집된 영상은 건너뛰고 남은 영상부터 자동으로 이어서 수집합니다.)*
* **상황 B. 전처리(Cell 3) 또는 형태소 분석기 설정(Cell 4) 도중 끊긴 경우**
  * `[Cell 1]` 실행 ➔ `[Cell 3]` 실행 ➔ `[Cell 4]` 실행
  * *(설명: Cell 2는 건너뛰고, 저장된 CSV를 불러와서 작업을 재개합니다.)*
* **상황 C. 모델 학습(Cell 5) 도중 끊긴 경우**
  * `[Cell 1]` ➔ `[Cell 3]` ➔ `[Cell 4]` ➔ `[Cell 5]` 실행
* **상황 D. 학습은 완료되었으나 시각화/결과 추출(Cell 6) 전에 끊긴 경우**
  * `[Cell 1]` ➔ `[Cell 6]` 실행
  * *(설명: Cell 6 코드 내부에 드라이브에 저장된 모델을 바로 불러오는 로직이 포함되어 있어 재학습 없이 즉시 결과를 추출할 수 있습니다.)*
"""

import os
import re
import pandas as pd
from googleapiclient.discovery import build
from google.colab import drive, userdata
from tqdm.notebook import tqdm
!pip install konlpy # Install konlpy
!pip install bertopic # Install bertopic
from konlpy.tag import Mecab
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer
from bertopic.representation import MaximalMarginalRelevance
import shutil # Added for clearing directory contents

# 드라이브 마운트
MOUNT_POINT = '/content/drive'

# If the mount point exists and contains files (not an empty directory),
# then clear its contents before attempting to mount.
if os.path.isdir(MOUNT_POINT) and os.listdir(MOUNT_POINT):
    print(f"⚠️ Warning: Mount point {MOUNT_POINT} is not empty. Attempting to clear its contents.")
    try:
        for item in os.listdir(MOUNT_POINT):
            item_path = os.path.join(MOUNT_POINT, item)
            if os.path.isfile(item_path) or os.islink(item_path):
                os.remove(item_path)
            elif os.path.isdir(item_path):
                shutil.rmtree(item_path)
        print(f"✅ Contents of {MOUNT_POINT} cleared.")
    except Exception as e:
        print(f"❌ Error clearing mount point contents: {e}. Mounting might still fail.")

# Now attempt to mount
drive.mount(MOUNT_POINT, force_remount=True)
WORK_DIR = os.path.join(MOUNT_POINT, 'MyDrive', 'AI통합교육')
os.makedirs(WORK_DIR, exist_ok=True)

# API 키 설정 확인
try:
    API_KEY = userdata.get('youtube')
except Exception:
    print("⚠️ 좌측 🔑(Secrets) 메뉴에 'youtube' 키를 등록하세요.")

import os

MODEL_PATH = '/content/drive/MyDrive/AI통합교육/bertopic_model_v1.pkl'

if os.path.exists(MODEL_PATH):
    print(f"✅ 모델 파일이 Google Drive에 존재합니다: {MODEL_PATH}")
else:
    print(f"⚠️ 모델 파일이 Google Drive에 없습니다: {MODEL_PATH}")
    print("💡 해결 방법: [Cell 5]를 다시 실행하여 모델이 정상적으로 저장되었는지 확인하십시오.")

# [Cell 2 - 관련성 전용판] 유튜브 수집: '쟁점/담론' 지표 제거, 관련성만으로 선별
#  - 변경 핵심: 댓글 수 임계값/정렬 제거, 정렬 = (키워드 관련도 점수 → API 관련성 순위)
from google.colab import userdata
from googleapiclient.discovery import build
import os
import re
import pandas as pd
from tqdm.notebook import tqdm

# 1. API 키 보안 호출
try:
    API_KEY = userdata.get('youtube')
except userdata.SecretNotFoundError:
    raise ValueError("⚠️ [오류] 좌측 🔑(Secrets) 메뉴에 'youtube' 키를 등록하세요.")

youtube = build('youtube', 'v3', developerKey=API_KEY)

# 2. 검색어: 주제 복합어 중심
search_query = (
    '"AI 디지털 교과서" OR "초중고 인공지능 교육" OR "학교 AI 교육" OR '
    '"생성형 AI 교실" OR "AI 교과서"'
)

# 2-1. 주제 적합성 2차 검증용 핵심 복합 키워드 (= 관련성 판정용. 쟁점과 무관)
CORE_KEYWORDS = [
    "AI 디지털 교과서", "디지털 교과서", "인공지능 교과서", "AI 교과서",
    "AI 교육", "인공지능 교육", "생성형 AI 교실",
    "학교 AI", "초중고 AI", "교실 AI", "학교 인공지능",
]

# --- 동작 옵션 ---
#  ★카테고리 필터는 '쟁점'이 아니라 콘텐츠 유형(뉴스/교육) 보조 필터입니다.★
#    순수 관련성만 보고 싶으면 False 로 두세요. (2차 키워드 검증으로 적합성은 이미 확보됨)
USE_CATEGORY_FILTER = True
CATEGORY_IDS = ['25', '27']  # 25=뉴스, 27=교육
TOP_N = 50                   # 최종 선별 영상 수
MIN_RELEVANCE_SCORE = 1      # 2차 검증 최소 점수(0이면 무관 → 제외)

def _normalize(text):
    return re.sub(r'\s+', '', str(text)).lower()

_NORM_KEYWORDS = [(kw, _normalize(kw)) for kw in CORE_KEYWORDS]

def relevance_score(title, description):
    """제목+설명의 핵심 복합어 포함 정도를 점수화 (제목 매칭 가중치 3, 설명 1)."""
    norm_title = _normalize(title)
    norm_all = _normalize(f"{title} {description}")
    score, matched = 0, []
    for kw_orig, kw_norm in _NORM_KEYWORDS:
        if kw_norm in norm_all:
            score += 3 if kw_norm in norm_title else 1
            matched.append(kw_orig)
    return score, matched

# 3. 경로 및 Resume 로직
WORK_DIR = '/content/drive/MyDrive/AI통합교육'
RAW_DATA_PATH = os.path.join(WORK_DIR, 'YouTube_Comments_Raw_meta.csv')
os.makedirs(WORK_DIR, exist_ok=True)

collected_video_ids = set()
if os.path.exists(RAW_DATA_PATH):
    try:
        existing_df = pd.read_csv(RAW_DATA_PATH)
        collected_video_ids = set(existing_df['video_id'].unique())
        print(f"기존 저장된 데이터 발견: 총 {len(existing_df)}개 댓글, {len(collected_video_ids)}개 영상 완료.")
    except Exception:
        print("기존 파일을 읽는 중 오류가 발생했습니다. 새로 시작합니다.")

# 4. 1/3 단계: 영상 탐색 (관련성 정렬 + 한국어/국내 + 페이지네이션)
print("🔍 1/3 단계: 관련성 기준 영상 탐색 중...")
video_ids, next_page_token = [], None
TARGET_SEARCH_COUNT = 150

while len(video_ids) < TARGET_SEARCH_COUNT:
    search_response = youtube.search().list(
        q=search_query, part="id", type="video",
        order="relevance",          # ★관련성 정렬 (조회수/날짜/평점 아님)★
        maxResults=50,
        relevanceLanguage="ko", regionCode="KR",
        pageToken=next_page_token,
    ).execute()
    video_ids += [item['id']['videoId'] for item in search_response.get('items', [])]
    next_page_token = search_response.get('nextPageToken')
    if not next_page_token:
        break

video_ids = list(dict.fromkeys(video_ids))            # 중복 제거(순서 유지)
api_rank = {vid: i for i, vid in enumerate(video_ids)}  # ★API 관련성 순위 보존★
print(f"  탐색된 후보 영상 수: {len(video_ids)}개")

# [수정된 5. 2/3 단계: 메타데이터 조회 및 확장 수집]
print("🔍 2/3 단계: 제목·설명 키워드로 관련성 재검증 및 메타데이터 수집 중...")
video_stats = []
for i in range(0, len(video_ids), 50):
    chunk_ids = ",".join(video_ids[i:i+50])
    stats_response = youtube.videos().list(part="snippet,statistics", id=chunk_ids).execute()

    for item in stats_response.get('items', []):
        snippet = item.get('snippet', {})
        stats = item.get('statistics', {})

        cat_id = snippet.get('categoryId')
        title = snippet.get('title', '')
        description = snippet.get('description', '')

        if USE_CATEGORY_FILTER and cat_id not in CATEGORY_IDS:
            continue

        score, matched = relevance_score(title, description)
        if score < MIN_RELEVANCE_SCORE:
            continue

        # --- [추가] 학술 연구용 핵심 메타정보 추출 ---
        channel_title = snippet.get('channelTitle', 'Unknown')
        published_at = snippet.get('publishedAt', '')
        tags = ", ".join(snippet.get('tags', []))
        view_count = int(stats.get('viewCount', 0))
        like_count = int(stats.get('likeCount', 0))
        comment_count = int(stats.get('commentCount', 0))
        # ----------------------------------------------

        video_stats.append({
            'video_id': item['id'],
            'title': title,
            'channel_title': channel_title,
            'published_at': published_at,
            'view_count': view_count,
            'like_count': like_count,
            'comment_count': comment_count,
            'tags': tags,
            'category_id': cat_id,
            'relevance_score': score,
            'matched_keywords': ", ".join(matched),
            'api_rank': api_rank.get(item['id'], 1e9)
        })

# [수정된 6. 정렬 및 메타데이터 전용 CSV 저장]
top_videos = sorted(
    video_stats,
    key=lambda x: (-x['relevance_score'], x['api_rank']),
)[:TOP_N]
target_video_ids = [v['video_id'] for v in top_videos]

# 영상 ID와 영상 제목을 매핑하는 딕셔너리 생성 (댓글 수집 단계용)
video_title_map = {v['video_id']: v['title'] for v in top_videos}

# --- [추가] 선정된 영상의 메타데이터를 별도 데이터프레임으로 영구 저장 ---
META_DATA_PATH = os.path.join(WORK_DIR, 'YouTube_Video_Metadata.csv')
pd.DataFrame(top_videos).to_csv(META_DATA_PATH, index=False, encoding='utf-8-sig')
print(f"✅ 관련성 검증 통과 영상: {len(video_stats)}개 → 최종 선별 상위 {len(target_video_ids)}개")
print(f"✅ 영상 메타데이터 저장 완료: {META_DATA_PATH}")
# ----------------------------------------------------------------

# 기 수집 영상 제외
remaining_video_ids = [vid for vid in target_video_ids if vid not in collected_video_ids]
print(f"  신규 수집 대상: {len(remaining_video_ids)}개")

# 7. 3/3 단계: 댓글 수집 및 영상 단위 실시간 저장 (메타데이터 포함)
print("📥 3/3 단계: 댓글 데이터 수집 시작...")
for vid in tqdm(remaining_video_ids, desc="영상별 댓글 수집 진행률"):
    comments_chunk = []
    try:
        comment_response = youtube.commentThreads().list(
            part="snippet", videoId=vid, maxResults=100, order="relevance", textFormat="plainText"
        ).execute()

        for item in comment_response.get('items', []):
            snippet = item['snippet']['topLevelComment']['snippet']
            comment_text = snippet.get('textDisplay', '')
            author_id = snippet.get('authorDisplayName', 'Unknown')  # 작성자 ID 추출
            video_title = video_title_map.get(vid, "제목 미상")        # 매핑된 영상 제목 추출

            comments_chunk.append({
                'video_id': vid,
                'video_title': video_title,
                'author_id': author_id,
                'text_content': comment_text
            })

        if comments_chunk:
            chunk_df = pd.DataFrame(comments_chunk)
            chunk_df.to_csv(
                RAW_DATA_PATH, mode='a',
                header=not os.path.exists(RAW_DATA_PATH),
                index=False, encoding='utf-8-sig'
            )
    except Exception:
        continue  # 댓글 사용 중지 영상 등 예외 처리

# 8. 수집 완료 후 현황 보고
if os.path.exists(RAW_DATA_PATH):
    final_df = pd.read_csv(RAW_DATA_PATH)
    print(f"\n🎯 수집 완료: 총 {len(final_df)}개의 댓글 데이터 확보됨.")
    display(final_df.head())
else:
    print("\n⚠️ 수집된 데이터가 없습니다. 검색어/CORE_KEYWORDS/카테고리 조건을 완화해 보세요.")

# [Cell 2.5 Alternative] 초고속 의미 유사도(Semantic Similarity) 기반 데이터 필터링
!pip install -q sentence-transformers

import pandas as pd
import os
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

WORK_DIR = '/content/drive/MyDrive/AI통합교육'
RAW_DATA_PATH = os.path.join(WORK_DIR, 'YouTube_Comments_Raw_meta.csv') # Corrected filename
FILTERED_DATA_PATH = os.path.join(WORK_DIR, 'YouTube_Comments_Filtered.csv')

# 1. 원시 데이터 로드
try:
    # Added header=0, engine='python' and on_bad_lines='warn' for robustness
    df_raw = pd.read_csv(RAW_DATA_PATH, header=0, sep=',', encoding='utf-8-sig', engine='python', on_bad_lines='warn')
    # 결측치 및 너무 짧은 단문 1차 제거
    df_raw = df_raw.dropna(subset=['text_content'])
    df_raw = df_raw[df_raw['text_content'].str.len() >= 10].reset_index(drop=True)
    print(f"✅ 기초 정제 완료: 총 {len(df_raw)}건의 댓글 분석 대기 중.")
except FileNotFoundError:
    raise ValueError("수집된 원시 데이터가 없습니다. [Cell 2]를 확인하세요.")

# 2. 다국어 임베딩 모델 로드 (BERTopic 사용 모델과 동일하여 일관성 유지)
print("⏳ 임베딩 모델을 불러오는 중입니다...")
model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

# 3. 기준 문장(Anchor Text) 정의
# 이 문장과 의미적으로 가까운 댓글들을 추출하게 됩니다.
anchor_text = "초등학교, 중학교, 고등학교 학교 현장의 인공지능(AI) 교육 도입과 AI 디지털 교과서 활용에 대한 교사, 학생, 학부모의 긍정적인 기대와 부정적인 문제점 우려"

# 4. 벡터 임베딩 변환 (코랩 GPU 활용 시 1~2분 소요)
print("🧠 기준 문장 및 댓글 전체의 문맥 벡터를 계산하고 있습니다...")
anchor_embedding = model.encode([anchor_text])
comment_embeddings = model.encode(df_raw['text_content'].tolist(), show_progress_bar=True)

# 5. 코사인 유사도 계산 (-1 ~ 1 사이의 값)
similarities = cosine_similarity(anchor_embedding, comment_embeddings)[0]
df_raw['similarity_score'] = similarities

# 6. 임계값(Threshold) 기반 필터링
# 유사도 점수가 0.25 이상인 문서만 '관련성 높음'으로 판단
# (일반적으로 0.2 ~ 0.3 사이에서 유의미한 군집이 형성됩니다)
THRESHOLD = 0.29
df_filtered = df_raw[df_raw['similarity_score'] >= THRESHOLD].copy()

# 유사도 순으로 정렬하여 저장
df_filtered = df_filtered.sort_values(by='similarity_score', ascending=False)
df_filtered.to_csv(FILTERED_DATA_PATH, index=False, encoding='utf-8-sig')

print(f"\n🎯 의미 유사도 필터링 완료!")
print(f"총 {len(df_raw)}건 중 문맥적으로 일치하는 {len(df_filtered)}건의 유효 데이터가 추출되었습니다.")

# 필터링된 결과물 최상위 5개와 최하위 5개 확인
print("\n[가장 관련성이 높은 댓글 Top 5]")
display(df_filtered[['text_content', 'similarity_score']].head())

print("\n[턱걸이로 통과된 댓글 (Threshold 근처)]")
display(df_filtered[['text_content', 'similarity_score']].tail())

# [Cell 3] 임베딩 성능 최적화를 위한 1차 텍스트 정제
# =====================================================================

!pip install kiwipiepy

import os
import re
import pandas as pd
from kiwipiepy import Kiwi

# WORK_DIR 는 Cell 1에서 정의되어 있다고 가정 (없으면 아래 주석 해제)
WORK_DIR = '/content/drive/MyDrive/AI통합교육'

# RAW_DATA_PATH = os.path.join(WORK_DIR, 'YouTube_Comments_Raw.csv')
FILTERED_DATA_PATH = os.path.join(WORK_DIR, 'YouTube_Comments_Filtered.csv')
CLEANED_DATA_PATH = os.path.join(WORK_DIR, 'YouTube_Comments_Cleaned.csv')

# # 원시 데이터 로드
# df = pd.read_csv(RAW_DATA_PATH)
# print(f"원시 데이터 로드: {len(df)}개")

# 1. LLM 필터링 데이터 로드
try:
    df = pd.read_csv(FILTERED_DATA_PATH)
    print(f"✅ 필터링된 유효 데이터 {len(df)}건 로드 완료.")
except FileNotFoundError:
    raise ValueError("필터링된 데이터가 없습니다. [Cell 2.5]를 먼저 실행하십시오.")

# ★수정 1: 정제 '이전에' 결측치부터 제거 (str(nan) → 'nan' 오염 방지)★
df = df.dropna(subset=['text_content']).reset_index(drop=True)

kiwi = Kiwi()

# Define stop_words_list here (copied from Cell 5 for coherence)
stop_words_list = [
    "영상", "진짜", "너무", "사람", "오늘", "보고", "대해", "밍꼬님", "저걸",
    "뚝배기", "대해서", "목살스텝", "yuta", "haechan", "the", "대하",
    "그리", "어요", "ㅂ니다", "연기", "니다" # 단일 글자 명사는 토크나이저(len>1)에서 이미 제거됨
]

def clean_text_for_embedding(text):
    # 1. URL 제거
    text = re.sub(r'http\S+', '', str(text))

    # 2. Kiwi로 형태소 분석 및 원형 복원
    # tokenize()에 normalize=True를 주면 오탈자 교정 및 원형 복원이 기본적으로 작동합니다.
    tokens = kiwi.tokenize(text, normalize_coda=True)

    cleaned_words = []
    for t in tokens:
        word = t.form  # 형태소 단어 (예: '먹다'의 '먹')
        pos = t.tag    # 품사 태그 (예: 'VV', 'NNG')

        # ① Kiwi 품사 태그 기준 제거 대상 (조사, 어미, 문장부호 등)
        # J로 시작하는 태그: 조사 (JKS, JKB, JX 등)
        # E로 시작하는 태그: 어미 (EC, EF, ETM 등)
        # S로 시작하는 태그: 부호 및 특수문자 (SF, SP, SO 등)
        if pos.startswith('J') or pos.startswith('E') or pos.startswith('S'):
            continue

        # ② 최종 필터링: 불용어 리스트에 없고, 2글자 이상인 것만 저장
        # (용언의 경우 '먹', '가' 처럼 어근만 남으므로 필요에 따라 길이 제한을 조절하세요)
        if word not in stop_words_list and len(word) > 1:
            cleaned_words.append(word)

    # 3. 다시 하나의 문장으로 결합
    return ' '.join(cleaned_words).strip()

print("전처리 작업 진행 중...")
df['cleaned_text'] = df['text_content'].apply(clean_text_for_embedding)

# 분석 불가능한 단문(길이 2 이하) 제거
df = df[df['cleaned_text'].str.len() > 2].reset_index(drop=True)

# ★수정 2: 중복 댓글(스팸/복붙) 제거 → 특정 토픽 과대 팽창 방지★
before = len(df)
df = df.drop_duplicates(subset=['cleaned_text']).reset_index(drop=True)
print(f"중복 제거: {before}개 → {len(df)}개")

# ★수정 3: 만약을 위한 'nan' 문자열 잔여 방어★
df = df[df['cleaned_text'].str.lower() != 'nan'].reset_index(drop=True)

# 정제된 데이터 드라이브 저장 (체크포인트)
df.to_csv(CLEANED_DATA_PATH, index=False, encoding='utf-8-sig')

print(f"✅ 전처리 완료: 총 {len(df)}개의 유효 데이터 확보됨. ({CLEANED_DATA_PATH} 저장 완료)")
display(df[['text_content', 'cleaned_text']].head())

# [Cell 4] 한국어 명사 토크나이저 정의 (★Cell 5보다 반드시 먼저 실행★)
# =====================================================================
!pip install kiwipiepy
from kiwipiepy import Kiwi

kiwi = Kiwi()  # konlpy(Okt) 대비 빠르고 Java 설정 불필요

def tokenize_korean_nouns(text):
    """일반명사(NNG)/고유명사(NNP)만 추출, 한 글자 명사는 노이즈로 보고 제외."""
    tokens = kiwi.tokenize(str(text))
    return [t.form for t in tokens if t.tag in ('NNG', 'NNP') and len(t.form) > 1]

# 동작 점검
print("토크나이저 테스트:", tokenize_korean_nouns("AI 디지털 교과서 도입에 대한 학부모들의 우려가 큽니다"))

# =====================================================================
# [Cell 5] BERTopic 토픽 모델링
# =====================================================================
import joblib  # (참고용, 실제 저장은 BERTopic 자체 메서드 사용)
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer
from bertopic.representation import MaximalMarginalRelevance

CLEANED_DATA_PATH = os.path.join(WORK_DIR, 'YouTube_Comments_Cleaned.csv')
MODEL_SAVE_PATH = os.path.join(WORK_DIR, 'bertopic_model_v1.pkl')  # ★pickle 단일 파일(통째 저장)★

EMBEDDING_MODEL_NAME = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"

# --- 동작 옵션 ---
REDUCE_OUTLIERS = True   # 이상치(-1) 재할당 여부. 잡음 신호를 보존하려면 False
CALC_PROBS = False       # ★확률 계산은 느리고 무거움. 꼭 필요할 때만 True★

# 정제 데이터 로드
print(f"정제된 데이터 로드 중: {CLEANED_DATA_PATH}")
df_cleaned = pd.read_csv(CLEANED_DATA_PATH)
df_cleaned = df_cleaned.dropna(subset=['cleaned_text']).reset_index(drop=True)
docs = df_cleaned['cleaned_text'].astype(str).tolist()
print(f"총 {len(docs)}개의 문서 로드 완료.")

# 1. 불용어 리스트 (★수정 4: 영문은 소문자로. CountVectorizer가 토큰을 소문자화하므로 'AI'→'ai'★)
stop_words_list = [
    "영상", "진짜", "너무", "사람", "오늘", "보고", "대해", "밍꼬님", "저걸",
    "뚝배기", "대해서", "목살스텝", "yuta", "haechan", "the", "대하",
    "그리", "어요", "ㅂ니다", "연기", "니다",# 단일 글자 명사는 토크나이저(len>1)에서 이미 제거됨
]

# 2. Vectorizer (한국어 명사 추출 + 불용어 + 최소 빈도)
vectorizer_model = CountVectorizer(
    tokenizer=tokenize_korean_nouns,
    stop_words=stop_words_list,
    min_df=5,           # 최소 5회 이상 등장 단어만 (노이즈 감소)
    lowercase=True,     # 명시 (영문 토큰 소문자화)
)

# 3. 파이프라인 구성
embedding_model = SentenceTransformer(EMBEDDING_MODEL_NAME)
umap_model = UMAP(n_neighbors=7, n_components=5, min_dist=0.0, metric='cosine', random_state=42)
hdbscan_model = HDBSCAN(
    min_cluster_size=15, metric='euclidean',
    cluster_selection_method='eom', prediction_data=True,
)
representation_model = MaximalMarginalRelevance(diversity=0.3)

topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    nr_topics=9,
    vectorizer_model=vectorizer_model,
    representation_model=representation_model,
    # language 인자 제거: embedding_model을 직접 지정하면 무시되므로 혼동 방지
    calculate_probabilities=CALC_PROBS,
    verbose=True,
    top_n_words=10,
)

# 4. 학습
print("\n🚀 BERTopic 모델 학습 시작... (수 분~수십 분 소요 가능)")
topics, probabilities = topic_model.fit_transform(docs)

# 4-1. 이상치(-1) 재할당 (선택)
#  ★주의: 전량 재할당은 '분류 불가' 잡음 신호까지 토픽에 섞어 경계를 흐릴 수 있음★
if REDUCE_OUTLIERS:
    n_outliers = topics.count(-1) if isinstance(topics, list) else int((pd.Series(topics) == -1).sum())
    print(f"이상치(-1) 개수: {n_outliers} → 재할당 수행")
    new_topics = topic_model.reduce_outliers(docs, topics)  # 기본 strategy='distributions'
    topic_model.update_topics(docs, topics=new_topics)
    # ★update_topics 이후 기존 probabilities는 더 이상 정합하지 않음.
    #   확률 분포가 필요하면 approximate_distribution 으로 재계산해야 함.★
    probabilities = None
else:
    print("이상치 재할당 생략 (잡음 신호 보존).")

print("✅ 토픽 모델링 완료.")

# 5. 모델 저장 (★pickle 통째 저장: 차원축소 모델·토픽 임베딩·원문 문서까지 전부 보존 → 시각화 정상 작동★)
#  - 단일 Colab 환경 분석에서는 경량화보다 '전체 보존'이 안전. 파일은 커질 수 있음(임베딩 모델 포함).
try:
    topic_model.save(MODEL_SAVE_PATH, serialization="pickle")
    print(f"\n✅ 모델 저장 완료: {MODEL_SAVE_PATH}")
    # 재로드 예시:  topic_model = BERTopic.load(MODEL_SAVE_PATH)
    # (대안) joblib 방식:  import joblib; joblib.dump(topic_model, MODEL_SAVE_PATH)
except Exception as e:
    print(f"⚠️ 모델 저장 실패: {e}\n경로 및 쓰기 권한을 확인해 주세요.")

# 6. 주요 토픽 정보 출력
print("\n주요 토픽 정보:")
display(topic_model.get_topic_info().head(10))

# =====================================================================
# [Cell] BERTopic 종합 시각화 및 토픽별 독립 엑셀 파일 추출 파이프라인
# =====================================================================
import os
import joblib
import re
import pandas as pd
from bertopic import BERTopic

# 1. 환경 및 파일 저장 경로 설정
WORK_DIR = '/content/drive/MyDrive/AI통합교육'
MODEL_PATH = os.path.join(WORK_DIR, 'bertopic_model_v1.pkl')
CLEANED_DATA_PATH = os.path.join(WORK_DIR, 'YouTube_Comments_Cleaned.csv')

# 2. 직렬화된 BERTopic 모델 객체 복원
print(f"드라이브에서 최적화된 모델을 로드합니다: {MODEL_PATH}")
try:
    topic_model = joblib.load(MODEL_PATH)
    print("✅ 모델 객체 로드 완료.")
except Exception as e:
    topic_model = BERTopic.load(MODEL_PATH)
    print("✅ BERTopic 로더를 통한 모델 복원 완료.")

# 3. 모델에 저장된 전체 토픽 메타정보 사전 확인
topic_info = topic_model.get_topic_info()
print("\n📊 [현재 모델의 8개 토픽 분포 현황]")
display(topic_info[['Topic', 'Count', 'Name']].head(9))

# =====================================================================
# 4. 아카데믹 시각화 출력 (인터랙티브 렌더링 및 번호 중첩 보정)
# =====================================================================
print("\n📈 시각화 자료를 화면에 렌더링합니다...")

# 가. 토픽별 c-TF-IDF 가중치 바차트 시각화
fig_barchart = topic_model.visualize_barchart(top_n_topics=8)
fig_barchart.show()

# 나. 인터토픽 디스턴스 맵 렌더링 (★T번호 마커 각인 강제 제어★)
fig_distance = topic_model.visualize_topics(top_n_topics=8)

if len(fig_distance.data) > 0:
    hover_labels = fig_distance.data[0].text if fig_distance.data[0].text is not None else fig_distance.data[0].hovertext
    if hover_labels is None:
        hover_labels = []

    topic_labels = []
    for label in hover_labels:
        match = re.search(r'^\d+|(?<=Topic\s)\d+', str(label))
        if match:
            topic_labels.append(f"<b>T{match.group(0)}</b>")  # 가독성 확보를 위한 볼드체 HTML 각인
        else:
            topic_labels.append("")

    fig_distance.update_traces(
        text=topic_labels,
        mode="markers+text",
        textposition="middle center",
        textfont=dict(size=12, color="black")
    )
fig_distance.show()

# 다. 계층적 덴드로그램 렌더링 (Ward 연결법 기반 위계성 매핑)
fig_hierarchy = topic_model.visualize_hierarchy(
    top_n_topics=8,
    color_threshold=1.5
)
fig_hierarchy.show()


# =====================================================================
# 5. [수량-정성 수렴 설계] 토픽 단위 개별 독립 엑셀 파일 분리 추출
# =====================================================================
print("\n🔄 정량적 토픽 분류 경계에 입각한 개별 엑셀 데이터 파티셔닝을 개시합니다.")

# 전처리 완료 원본 데이터프레임 로드 및 토픽 귀속 정보 정합
df_cleaned = pd.read_csv(CLEANED_DATA_PATH)
df_cleaned = df_cleaned.dropna(subset=['cleaned_text']).reset_index(drop=True)
docs = df_cleaned['cleaned_text'].astype(str).tolist()

# 개별 도큐먼트의 사후 분류 정보 추출 및 바인딩
doc_info = topic_model.get_document_info(docs)
df_cleaned['Assigned_Topic'] = doc_info['Topic'].values

# 💡 [학술적 명명 매트릭스] 각 토픽 번호에 대응하는 연구자 정의 대범주 라벨링
topic_metadata = {
    0: "0",
    1: "1",
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7"
}

print("\n💾 [토픽별 독립 엑셀 파일 생성 결과]")
unique_topics = sorted(df_cleaned['Assigned_Topic'].unique())

for topic_id in unique_topics:
    # 이상치(Outlier, Topic -1) 처리 분기 설정
    if topic_id == -1:
        topic_label = "이상치_미분류_코퍼스"
    else:
        topic_label = topic_metadata.get(topic_id, "미정의_토픽_영역")

    # 해당 토픽에 귀속된 하부 코퍼스만 마스킹 필터링
    topic_df = df_cleaned[df_cleaned['Assigned_Topic'] == topic_id].copy()

    # 질적내용분석(귀납적 코딩)용 핵심 변수 투영 및 소속 정렬
    export_df = topic_df[['video_title', 'author_id', 'Assigned_Topic', 'text_content']]
    export_df = export_df.sort_values(by='author_id')

    # 파일 내보내기 수행
    file_name = f"토픽{topic_id}_{topic_label}_질적분석용.xlsx"
    out_path = os.path.join(WORK_DIR, file_name)
    export_df.to_excel(out_path, index=False)

    print(f"✅ 토픽 {topic_id:2d} | 표본크기(N={len(export_df):3d}건) -> 내보내기 완료: {file_name}")

print("\n🎯 프로세스가 정상적으로 종결되었습니다. 생성된 토픽별 개별 엑셀 파일을 기초 자료로 삼아 정성적 수렴 분석을 전개하십시오.")